version: '3.5'

services:
  survey-app:
    build:
      - context: .
      - dockerfile: ./dockerfile
      - target: final
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT: Development
      - ASPNETCORE_URLS: http://+:80
      - CONNECTIONSTRING: "Host=localhost;Port=5432;Database=survey_db_test;Username=dev;Password=dev"
